### ISSUE TITLE
position does not change

### ISSUE THREAD

**Issue by jemshit** [friendlyrobotnyc/TinyDancer#48] opened 2016-11-01 12:27 UTC
view position does not change even if i change it from Builder

**Comment by digitalbuddha** [comment] 2016-11-03 15:03
The issue seems to be caused by both setting the gravity & x+y position. I'll have a fix in next version to ignore the gravity if there is a user configured starting x+y.  Thanks for reporting!

**Comment by brianPlummer** [comment] 2017-02-11 22:10
@jemshit fixed in current master branch and will go with the 0.1.1 release tomorrow or the next

**Closed** 2017-02-11 22:09 UTC
